
export const ProjectsDetails = [
    {id:1, image: require( "../../assets/projects/the-first-project/screen-2.png"), images1:[
        {img1: require("../../assets/projects/the-first-project/screeen-1.png")},
        {img2: require("../../assets/projects/the-first-project/screen-2.png")},
        {img2: require("../../assets/projects/the-first-project/screen-3.png")},
        {img2: require("../../assets/projects/the-first-project/screen-4.png")},
        {img2: require("../../assets/projects/the-first-project/screen-5.png")},
        {img2: require("../../assets/projects/the-first-project/screen-6.png")}
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "The first PROJECT", description1: "This is my first project, and it consists of 4 sections, and this project was for learning."},

    {id: 2, image: require("../../assets/projects/the-2-project/screen-1.png"), images1:[
        {img1: require("../../assets/projects/the-2-project/screen-1.png")},
        {img2: require("../../assets/projects/the-2-project/screen-2.png")},
        {img3: require("../../assets/projects/the-2-project/screen-3.png")},
        {img4: require("../../assets/projects/the-2-project/screen-4.png")},
        {img5: require("../../assets/projects/the-2-project/screen-5.png")},
        {img6: require("../../assets/projects/the-2-project/screen-6.png")},
        {img7: require("../../assets/projects/the-2-project/screen-7.png")},
        {img8: require("../../assets/projects/the-2-project/screen-8.png")},
        {img9: require("../../assets/projects/the-2-project/screen-9.png")},
        {img10: require("../../assets/projects/the-2-project/screen-10.png")},
        {img11: require("../../assets/projects/the-2-project/screen-11.png")},
        {img12: require("../../assets/projects/the-2-project/screen-12.png")},
        {img13: require("../../assets/projects/the-2-project/screen-13png.png")},
        {img14: require("../../assets/projects/the-2-project/screen-14.png")},
        {img16: require("../../assets/projects/the-2-project/screen-15.png")},
        {img16: require("../../assets/projects/the-2-project/screen-16.png")},
        {img17: require("../../assets/projects/the-2-project/screen-17.png")},
        {img18: require("../../assets/projects/the-2-project/screen-18.png")},
        {img19: require("../../assets/projects/the-2-project/screen-19.png")},
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "The second PROJECT", description1: "This is my second project, and it has more features than the first project, consisting of 7 sections, and this project was for learning."},

    {id: 3, image: require( "../../assets/projects/the-3-project/screen-1.png"), images1:[
        {img1: require("../../assets/projects/the-3-project/screen-1.png")},
        {img2: require("../../assets/projects/the-3-project/screen-2.png")},
        {img3: require("../../assets/projects/the-3-project/screen-3.png")},
        {img4: require("../../assets/projects/the-3-project/screen-4.png")},
        {img5: require("../../assets/projects/the-3-project/screen-5.png")},
        {img6: require("../../assets/projects/the-3-project/screen-6.png")},
        {img7: require("../../assets/projects/the-3-project/screen-7.png")},
        {img8: require("../../assets/projects/the-3-project/screen-8.png")},
        {img9: require("../../assets/projects/the-3-project/screen-9.png")},
        {img10: require("../../assets/projects/the-3-project/screen-10.png")},
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "The third PROJECT", description1: "This is my third project, and it consists of 8 sections, and this project was for learning."},

    {id: 4, image: require("../../assets/projects/the-4-project/screen-1.png"), images1: [
        {img1: require("../../assets/projects/the-4-project/screen-1.png")},
        {img2: require("../../assets/projects/the-4-project/screen-2.png")},
        {img3: require("../../assets/projects/the-4-project/screen-3.png")},
        {img4: require("../../assets/projects/the-4-project/screen-4.png")},
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "The fourth PROJECT", description1: "This is the fourth project for me, and it consists of a very simple registration page, with the sole purpose of learning." },

    {id: 5, image: require("../../assets/projects/the-5-project/screen-1.png") , images1: [
        {img1: require("../../assets/projects/the-5-project/screen-1.png")},
        {img2: require("../../assets/projects/the-5-project/screen-2.png")},
        {img3: require("../../assets/projects/the-5-project/screen-3.png")},
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "The fifth PROJECT", description1: "This is the fifth project for me, and it consists of a very simple landing page."},

    {id: 6, image: require("../../assets/projects/the-6-project/screen-1.png") , images1: [
        {img1: require("../../assets/projects/the-6-project/screen-1.png")},
        {img2: require("../../assets/projects/the-6-project/screen-2.png")},
        {img3: require("../../assets/projects/the-6-project/screen-3.png")},
        {img4: require("../../assets/projects/the-6-project/screen-4.png")},
    ], title: "I used HTML, CSS & JS", category: "HTML, CSS, JS", name: "Iphones PROJECT", description1: "This project is about when you tap on the image of the iPhone below the background color changes to the color of the iPhone, and also the image of the iPhone changes."},

    {id: 7, image: require("../../assets/projects/the-7-project/screen-1.png") , images1: [
        {img1: require("../../assets/projects/the-7-project/screen-1.png")},
        {img2: require("../../assets/projects/the-7-project/screen-2.png")},
        {img3: require("../../assets/projects/the-7-project/screen-3.png")},
        {img4: require("../../assets/projects/the-7-project/screen-4.png")},
        {img5: require("../../assets/projects/the-7-project/screen-5.png")},
    ], title: "I used HTML, CSS & JS", category: "HTML, CSS, JS", name: "Moon PROJECT", description1: "The idea of this project is that there are 3 mountains, a boat, and a moon. When you scroll, the mountains move to the left, the boat moves to the right, and the moon descends below while displaying the name."},

    {id: 8, image: require("../../assets/projects/the-8-project/screen-1.png") , images1: [
        {img1: require("../../assets/projects/the-8-project/screen-1.png")},
        {img2: require("../../assets/projects/the-8-project/screen-2.png")},
        {img3: require("../../assets/projects/the-8-project/screen-3.png")},
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "Landing page PROJECT", description1: "This project, it consists of a very simple landing page."},

    {id: 9, image: require("../../assets/projects/the-9-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-9-project/screen1.png")}
    ], title: "I only used HTML, CSS", category: "HTML, CSS", name: "Landing page PROJECT", description1: "This project, it consists of a very simple landing page, and this project for learning."}, 

    {id: 10, image: require("../../assets/projects/the-10-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-10-project/screen1.png")},
        {img2: require("../../assets/projects/the-10-project/screen2.png")},
        {img3: require("../../assets/projects/the-10-project/screen3.png")},
        {img4: require("../../assets/projects/the-10-project/screen4.png")},
        {img5: require("../../assets/projects/the-10-project/screen5.png")},
        {img6: require("../../assets/projects/the-10-project/screen6.png")},
        {img7: require("../../assets/projects/the-10-project/screen7.png")},
    ], title: "I only used BOOTSTRAP.", category: "BOOTSTRAP", name: "Bootstrap PROJECT", description1: "This project consists of 4 sections, and there is also a slider." },

    {id: 11, image: require("../../assets/projects/the-11-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-11-project/screen1.png")},
        {img2: require("../../assets/projects/the-11-project/screen2.png")},
        {img3: require("../../assets/projects/the-11-project/screen3.png")},
        {img4: require("../../assets/projects/the-11-project/screen4.png")},
        {img5: require("../../assets/projects/the-11-project/screen5.png")},
        {img6: require("../../assets/projects/the-11-project/screen6.png")},
        {img8: require("../../assets/projects/the-11-project/screen8.png")},
        {img9: require("../../assets/projects/the-11-project/screen9.png")},
        {img10: require("../../assets/projects/the-11-project/screen10.png")},
    ], title: "I used HTML, CSS & JS", category: "HTML, CSS, JS", name: "CRUDs PROJECT", description1: "This project is in the form where you can enter the title, price, taxes, ads, discount, count, and category. When you create the product, it will be displayed on the screen, and you can update and delete it. You can also delete all products, and you can search for a product by category or title."},

    {id: 12, image: require("../../assets/projects/the-12-project/screen1.jpeg") , images1: [
        {img1: require("../../assets/projects/the-12-project/screen1.jpeg")},
        {img2: require("../../assets/projects/the-12-project/screen2.jpeg")},
        {img3: require("../../assets/projects/the-12-project/screen3.jpeg")},
        {img4: require("../../assets/projects/the-12-project/screen4.jpeg")}
    ], title: "I used React.js", category: "React.js", name: "Todo list PROJECT", description1: "This project is a todo list. You will write your todos, and then they will appear on the screen. You can delete them, and when you finish a todo, you can click on it to mark it as done with a line through it. Then, you will find three buttons:    The 'All' button shows all the todos you have written. The 'Active' button displays todos that you haven't completed yet. The 'Complete' button shows todos that you have marked as done. "},

    {id: 13, image: require("../../assets/projects/the-13-project/home1.png") , images1: [
        {img1: require("../../assets/projects/the-13-project/home1.png")},
        {img2: require("../../assets/projects/the-13-project/home2.png")},
        {img3: require("../../assets/projects/the-13-project/home3.png")},
        {img4: require("../../assets/projects/the-13-project/home4.png")},
        {img5: require("../../assets/projects/the-13-project/about1.png")},
        {img6: require("../../assets/projects/the-13-project/about2.png")},
        {img8: require("../../assets/projects/the-13-project/about3.png")},
        {img9: require("../../assets/projects/the-13-project/about4.png")},
        {img10: require("../../assets/projects/the-13-project/tours1.png")},
        {img11: require("../../assets/projects/the-13-project/tours2.png")},
        {img12: require("../../assets/projects/the-13-project/tours3.png")},
        {img13: require("../../assets/projects/the-13-project/tours4.png")},
        {img14: require("../../assets/projects/the-13-project/tours5.png")},
        {img15: require("../../assets/projects/the-13-project/contact1.png")},
        {img16: require("../../assets/projects/the-13-project/contact2.png")},
        {img17: require("../../assets/projects/the-13-project/contact3.png")},
    ], title: "I used HTML, CSS & JS", category: "HTML, CSS, JS", name: "Holiday PROJECT", description1: "This project consists of 4 pages, which are home, about, tours, and contact pages, and each page consists of 3 to 4 sections" },

    {id: 14, image: require("../../assets/projects/the-14-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-14-project/screen1.png")},
        {img2: require("../../assets/projects/the-14-project/screen2.png")},
        {img3: require("../../assets/projects/the-14-project/screen3.png")},
        {img4: require("../../assets/projects/the-14-project/screen4.png")},
        {img5: require("../../assets/projects/the-14-project/screen5.png")},
        {img6: require("../../assets/projects/the-14-project/screen6.png")},
        {img8: require("../../assets/projects/the-14-project/screen8.png")},
    ], title: "I used HTML, CSS, JS & JQUERY", category: "HTML, CSS, JS, JQUERY", name: "Festeva Live PROJECT", description1: "This project, it consists 6 sections, and there is many features in this project."},

    {id: 15, image: require("../../assets/projects/the-15-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-15-project/screen1.png")},
        {img2: require("../../assets/projects/the-15-project/screen2.png")},
        {img3: require("../../assets/projects/the-15-project/screen3.png")},
        {img4: require("../../assets/projects/the-15-project/screen4.png")},
        {img5: require("../../assets/projects/the-15-project/screen5.png")},
        {img6: require("../../assets/projects/the-15-project/screen6.png")},
        {img7: require("../../assets/projects/the-15-project/screen7.png")},
        {img8: require("../../assets/projects/the-15-project/screen8.png")},
        {img9: require("../../assets/projects/the-15-project/screen9.png")},
        {img10: require("../../assets/projects/the-15-project/screen10.png")},
        {img11: require("../../assets/projects/the-15-project/screen11.png")},
        {img12: require("../../assets/projects/the-15-project/screen12.png")},
        {img13: require("../../assets/projects/the-15-project/screen13.png")},
    ], title: "I used HTML, CSS, JS & JQUERY", category: "HTML, CSS, JS, JQUERY",  name: "This PROJECT for testing", description1: "This project, it consists 5 sections, and also login and logout." },

    {id: 16, image: require("../../assets/projects/the-16-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-16-project/screen1.png")},
        {img2: require("../../assets/projects/the-16-project/screen2.png")},
        {img3: require("../../assets/projects/the-16-project/screen3.png")},
        {img4: require("../../assets/projects/the-16-project/screen4.png")},
        {img5: require("../../assets/projects/the-16-project/screen5.png")},
        {img6: require("../../assets/projects/the-16-project/screen6.png")},
        {img7: require("../../assets/projects/the-16-project/screen7.png")},
    ], title: "I used React.js", category: "React.js", name: "Card-app PROJECT", description1: "This project consists of two pages. The idea of the project is that on the home page, you have some products, and in each product, you will find an 'add to cart' button. When you click on it, you will find it in the cart page, and you can delete it and everything else. You will also find the prices of all the products above."},

    {id: 17, image: require("../../assets/projects/the-17-project/screen1.png") , images1: [
        {img1: require("../../assets/projects/the-17-project/screen1.png")},
        {img2: require("../../assets/projects/the-17-project/screen2.png")},
        {img3: require("../../assets/projects/the-17-project/screen3.png")},
        {img4: require("../../assets/projects/the-17-project/screen4.png")},
        {img5: require("../../assets/projects/the-17-project/screen5.png")},
        {img6: require("../../assets/projects/the-17-project/screen6.png")},
        {img7: require("../../assets/projects/the-17-project/screen7.png")},
        {img8: require("../../assets/projects/the-17-project/screen8.png")},
        {img9: require("../../assets/projects/the-17-project/screen9.png")},
        {img10: require("../../assets/projects/the-17-project/screen10.png")},
        {img11: require("../../assets/projects/the-17-project/screen11.png")},
        {img12: require("../../assets/projects/the-17-project/screen12.png")},
        {img13: require("../../assets/projects/the-17-project/screen13.png")},
        {img14: require("../../assets/projects/the-17-project/screen14.png")},
        {img16: require("../../assets/projects/the-17-project/screen15.png")},
        {img16: require("../../assets/projects/the-17-project/screen16.png")},
        {img17: require("../../assets/projects/the-17-project/screen17.png")},
        {img18: require("../../assets/projects/the-17-project/screen18.png")},
        {img19: require("../../assets/projects/the-17-project/screen19.png")},
        {img20: require("../../assets/projects/the-17-project/screen20.png")},
        {img21: require("../../assets/projects/the-17-project/screen21.png")},
        {img22: require("../../assets/projects/the-17-project/screen22.png")},
        {img23: require("../../assets/projects/the-17-project/screen23.png")},
        {img24: require("../../assets/projects/the-17-project/screen24.png")},
        {img25: require("../../assets/projects/the-17-project/screen25.png")},
        {img26: require("../../assets/projects/the-17-project/screen26.png")},
        {img27: require("../../assets/projects/the-17-project/screen27.png")},
        {img28: require("../../assets/projects/the-17-project/screen28.png")},
        {img29: require("../../assets/projects/the-17-project/screen29.png")},
        {img30: require("../../assets/projects/the-17-project/screen30.png")}
    ], title: "I used React.js with Material-UI", category: "React.js, Material-UI", name: "Dashboard-App", description1: "This project consists of 11 pages, and each page has many features such as charts, a world map, and there is also a result, as well as a form. Of course, you cannot submit the data in the form until all the fields are not empty, and the entire website has a light and dark mode."},

    {id: 18, image: require("../../assets/projects/the-18-project/admin1.png") , images1: [
        {img1: require("../../assets/projects/the-18-project/logout1.png")},
        {img2: require("../../assets/projects/the-18-project/logout2.png")},
        {img3: require("../../assets/projects/the-18-project/logout3.png")},
        {img4: require("../../assets/projects/the-18-project/logout4.png")},
        {img5: require("../../assets/projects/the-18-project/logout5.png")},
        {img6: require("../../assets/projects/the-18-project/logout6.png")},
        {img7: require("../../assets/projects/the-18-project/logout7.png")},
        {img8: require("../../assets/projects/the-18-project/logout8.png")},
        {img9: require("../../assets/projects/the-18-project/logout9.png")},
        {img10: require("../../assets/projects/the-18-project/logout10.png")},
        {img11: require("../../assets/projects/the-18-project/logout11.png")},
        {img12: require("../../assets/projects/the-18-project/logout12.png")},
        {img13: require("../../assets/projects/the-18-project/logout13.png")},
        {img14: require("../../assets/projects/the-18-project/logout14.png")},
        {img15: require("../../assets/projects/the-18-project/logout15.png")},
        {img16: require("../../assets/projects/the-18-project/logout16.png")},
        {img17: require("../../assets/projects/the-18-project/logout17.png")},
        {img18: require("../../assets/projects/the-18-project/logout18.png")},
        {img19: require("../../assets/projects/the-18-project/logout19.png")},
        {img20: require("../../assets/projects/the-18-project/logout20.png")},
        {img21: require("../../assets/projects/the-18-project/logout21.png")},
        {img22: require("../../assets/projects/the-18-project/logout22.png")},
        {img23: require("../../assets/projects/the-18-project/logout23.png")},
        {img24: require("../../assets/projects/the-18-project/logout24.png")},
        {img25: require("../../assets/projects/the-18-project/logout25.png")},
        {img26: require("../../assets/projects/the-18-project/user1.png")},
        {img27: require("../../assets/projects/the-18-project/user2.png")},
        {img28: require("../../assets/projects/the-18-project/user3.png")},
        {img29: require("../../assets/projects/the-18-project/user4.png")},
        {img30: require("../../assets/projects/the-18-project/user5.png")},
        {img31: require("../../assets/projects/the-18-project/user6.png")},
        {img32: require("../../assets/projects/the-18-project/user7.png")},
        {img33: require("../../assets/projects/the-18-project/user8.png")},
        {img34: require("../../assets/projects/the-18-project/user9.png")},
        {img35: require("../../assets/projects/the-18-project/user10.png")},
        {img36: require("../../assets/projects/the-18-project/user11.png")},
        {img37: require("../../assets/projects/the-18-project/user12.png")},
        {img38: require("../../assets/projects/the-18-project/user13.png")},
        {img39: require("../../assets/projects/the-18-project/user14.png")},
        {img40: require("../../assets/projects/the-18-project/user15.png")},
        {img41: require("../../assets/projects/the-18-project/admin1.png")},
        {img42: require("../../assets/projects/the-18-project/admin2.png")},
        {img43: require("../../assets/projects/the-18-project/admin3.png")},
        {img44: require("../../assets/projects/the-18-project/admin4.png")},
        {img45: require("../../assets/projects/the-18-project/admin5.png")},
        {img46: require("../../assets/projects/the-18-project/admin6.png")},
        {img47: require("../../assets/projects/the-18-project/admin7.png")},
        {img48: require("../../assets/projects/the-18-project/admin8.png")},
        {img49: require("../../assets/projects/the-18-project/admin9.png")},
        {img50: require("../../assets/projects/the-18-project/admin10.png")},
        {img51: require("../../assets/projects/the-18-project/admin11.png")},
        {img52: require("../../assets/projects/the-18-project/admin12.png")},
        {img53: require("../../assets/projects/the-18-project/admin13.png")},
        {img54: require("../../assets/projects/the-18-project/admin14.png")},
        {img55: require("../../assets/projects/the-18-project/admin15.png")},
        {img56: require("../../assets/projects/the-18-project/admin16.png")},
        {img57: require("../../assets/projects/the-18-project/admin17.png")},
        {img58: require("../../assets/projects/the-18-project/admin18.png")},
        {img59: require("../../assets/projects/the-18-project/admin19.png")},
        {img60: require("../../assets/projects/the-18-project/admin20.png")},
        {img61: require("../../assets/projects/the-18-project/admin21.png")},
        {img62: require("../../assets/projects/the-18-project/admin22.png")},
        {img63: require("../../assets/projects/the-18-project/admin23.png")},
        {img64: require("../../assets/projects/the-18-project/admin24.png")},
        {img65: require("../../assets/projects/the-18-project/admin25.png")},
        {img66: require("../../assets/projects/the-18-project/admin26.png")},
        {img67: require("../../assets/projects/the-18-project/admin27.png")},
        {img68: require("../../assets/projects/the-18-project/admin28.png")},
        {img69: require("../../assets/projects/the-18-project/admin29.png")},
        {img70: require("../../assets/projects/the-18-project/admin30.png")},
        {img71: require("../../assets/projects/the-18-project/admin31.png")},
        {img72: require("../../assets/projects/the-18-project/admin32.png")},
        {img73: require("../../assets/projects/the-18-project/admin33.png")},
        {img74: require("../../assets/projects/the-18-project/admin34.png")},
        {img75: require("../../assets/projects/the-18-project/admin35.png")},
        {img76: require("../../assets/projects/the-18-project/admin36.png")},
        {img77: require("../../assets/projects/the-18-project/admin37.png")},
        {img78: require("../../assets/projects/the-18-project/admin38.png")},
        {img79: require("../../assets/projects/the-18-project/admin39.png")},
        {img80: require("../../assets/projects/the-18-project/admin40.png")},
        {img81: require("../../assets/projects/the-18-project/admin41.png")},
        {img82: require("../../assets/projects/the-18-project/admin42.png")},
        {img83: require("../../assets/projects/the-18-project/admin43.png")},
        {img84: require("../../assets/projects/the-18-project/admin44.png")},
        {img85: require("../../assets/projects/the-18-project/admin45.png")},
        {img86: require("../../assets/projects/the-18-project/admin46.png")},
        {img87: require("../../assets/projects/the-18-project/admin47.png")},
        {img88: require("../../assets/projects/the-18-project/admin48.png")},
        {img89: require("../../assets/projects/the-18-project/admin49.png")},
        {img90: require("../../assets/projects/the-18-project/admin50.png")},
        {img91: require("../../assets/projects/the-18-project/admin51.png")},
        {img92: require("../../assets/projects/the-18-project/admin52.png")},
        {img93: require("../../assets/projects/the-18-project/admin53.png")},
        {img94: require("../../assets/projects/the-18-project/admin54.png")},
        {img95: require("../../assets/projects/the-18-project/admin55.png")},
        {img96: require("../../assets/projects/the-18-project/admin56.png")},
        {img97: require("../../assets/projects/the-18-project/admin57.png")},
        {img98: require("../../assets/projects/the-18-project/admin58.png")},
        {img99: require("../../assets/projects/the-18-project/admin59.png")},
        {img100: require("../../assets/projects/the-18-project/admin60.png")}
    ], title: "I used React.js, Node.js, Express.js, redux-toolkit & MongoDB", category: "React.js, Express.js", name: "Blog-App", description1: "When there is no user logged in on the website, they will only find two pages: home and posts. They won't be able to perform any actions such as liking, commenting, or creating a post. They won't have control over the website until they register.<br />-When a user is not an admin, they can like, comment, create posts, edit their own comments, remove likes, delete and edit their posts, view content, edit their profile picture, edit post images, and delete their account. <br /> -When the user is the admin, they can perform everything. They can view all user profiles, delete comments, like posts, and do everything that a regular user can do. The admin also has an admin dashboard page where they can see all users, comments, posts, and categories. They can delete specific users, view their profiles, and also remove users. Additionally, they can view all posts, see individual posts, delete them, view all comments, delete them, and view all categories. They can also add a specific category."},

    {id: 19, image: require("../../assets/projects/the-19-project/home1.png"), images1: [
        {img1: require("../../assets/projects/the-19-project/home1.png")},
        {img1: require("../../assets/projects/the-19-project/home2.png")},
        {img1: require("../../assets/projects/the-19-project/home3.png")},
        {img1: require("../../assets/projects/the-19-project/about1.png")},
        {img1: require("../../assets/projects/the-19-project/about2.png")},
        {img1: require("../../assets/projects/the-19-project/about3.png")},
        {img1: require("../../assets/projects/the-19-project/about4.png")},
        {img1: require("../../assets/projects/the-19-project/services1.png")},
        {img1: require("../../assets/projects/the-19-project/services2.png")},
        {img1: require("../../assets/projects/the-19-project/services3.png")},
        {img1: require("../../assets/projects/the-19-project/services4.png")},
        {img1: require("../../assets/projects/the-19-project/services5.png")},
        {img1: require("../../assets/projects/the-19-project/test1.png")},
        {img1: require("../../assets/projects/the-19-project/test2.png")},
        {img1: require("../../assets/projects/the-19-project/test3.png")},
        {img1: require("../../assets/projects/the-19-project/test4.png")},
        {img1: require("../../assets/projects/the-19-project/contact1.png")},
        {img1: require("../../assets/projects/the-19-project/contact2.png")},
        {img1: require("../../assets/projects/the-19-project/contact3.png")},
        {img1: require("../../assets/projects/the-19-project/contact4.png")},
    ], title: "I used HTML, CSS & JS", category: "HTML, CSS, JS", name: "Training PROJECT", description1: "This project consists of 5 pages, with each page comprising approximately 3 to 4 sections." },

    {id: 20, image: require("../../assets/projects/the-20-project/screen1.png"), images1: [
        {img1: require("../../assets/projects/the-20-project/screen1.png")},
        {img1: require("../../assets/projects/the-20-project/screen2.png")},
        {img1: require("../../assets/projects/the-20-project/screen3.png")},
        {img1: require("../../assets/projects/the-20-project/screen4.png")},
        {img1: require("../../assets/projects/the-20-project/screen5.png")},
        {img1: require("../../assets/projects/the-20-project/screen6.png")}
    ], title: "I used HTML, CSS, OOP in JS", category: "HTML, CSS, JS", name: "Simple game PROJECT", description1: "This project is a simple game with two characters, each having an 'attack' and 'health' attribute. When a character performs an 'attack' on the other character, the health of the second character decreases. Additionally, a character can use 'health' on themselves until they die, and they cannot use it again."}
]